# Build image
FROM microsoft/dotnet:2.2-sdk AS builder
WORKDIR /app

# Copy files
COPY . ./

RUN dotnet restore
RUN dotnet build

WORKDIR /app/Marten.WebApi
RUN dotnet publish -c Debug -o out

# Build runtime image
FROM microsoft/dotnet:2.2-sdk
WORKDIR /app
COPY --from=builder /app/Marten.WebApi/out .
ENV ASPNETCORE_URLS="http://*:5000"
ENTRYPOINT ["dotnet", "Marten.WebApi.dll"]
